from __future__ import annotations

from collections.abc import Buffer, Iterable, Mapping, Sequence
from typing import Any

from typing import ClassVar

class Blob:
    @classmethod
    def new(cls, blobParts: Iterable[Any], options: Any) -> Blob: ...
    async def arrayBuffer(self) -> int: ...

class CSSStyleSheet:
    @classmethod
    def new(cls) -> CSSStyleSheet: ...
    def replaceSync(self, text: str) -> None: ...

class Event:
    @classmethod
    def new(cls, name: str) -> Event: ...

class File(Blob):
    name: str = ...

class FileList:
    length: int = ...
    def item(self, index: int) -> File: ...

class Node:
    TEXT_NODE: ClassVar[int] = ...
    nodeType: int
    nodeValue: str
    def append(self, *args: Node | str) -> None: ...

class NodeFilter:
    SHOW_TEXT: ClassVar[int] = ...

class Text(Node): ...

class Uint8Array:
    @classmethod
    def new(cls, bytes_: Buffer) -> Uint8Array: ...

class URL:
    @classmethod
    def createObjectURL(cls, object: Any) -> str: ...
    @classmethod
    def revokeObjectURL(cls, url: str) -> None: ...

class Location:
    def reload(self) -> None: ...

location: Location

class console:
    @staticmethod
    def assert_(assertion: bool, *arg: Any) -> None: ...
    @staticmethod
    def clear() -> None: ...
    @staticmethod
    def count(label: str | None = ...) -> None: ...
    @staticmethod
    def countReset(label: str | None = ...) -> None: ...
    @staticmethod
    def debug(*args: Any) -> None: ...
    @staticmethod
    def dir(obj: object, options: Mapping[str, bool | int | None] | None = ...) -> None: ...
    @staticmethod
    def dirxml(obj: object) -> None: ...
    @staticmethod
    def error(*args: Any) -> None: ...
    @staticmethod
    def exception(*args: Any) -> None: ...
    @staticmethod
    def group(label: str | None = ...) -> None: ...
    @staticmethod
    def groupCollapsed(label: str | None = ...) -> None: ...
    @staticmethod
    def groupEnd() -> None: ...
    @staticmethod
    def info(*args: Any) -> None: ...
    @staticmethod
    def log(*args: Any) -> None: ...
    @staticmethod
    def profile(profileName: str | None = ...) -> None: ...
    @staticmethod
    def profileEnd(profileName: str | None = ...) -> None: ...
    @staticmethod
    def table(data: object, columns: Sequence[int] | Sequence[str] | None = ...) -> None: ...
    @staticmethod
    def time(label: str | None = ...) -> None: ...
    @staticmethod
    def timeEnd(label: str | None = ...) -> None: ...
    @staticmethod
    def timeLog(*args: object) -> None: ...
    @staticmethod
    def timeStamp(*args: object) -> None: ...
    @staticmethod
    def trace(*args: object) -> None: ...
    @staticmethod
    def warn(*args: Any) -> None: ...
