from __future__ import annotations

from typing import no_type_check

from js import Node

class ArrayBuffer:
    def to_bytes(self) -> bytes: ...

class JsNull: ...

@no_type_check
class JsProxy:
    nodeType: int
    nodeValue: str
    def append(self, *args: Node | str) -> None: ...
    async def arrayBuffer(self) -> ArrayBuffer: ...
    def to_bytes(self) -> bytes: ...
    def to_py(self) -> object: ...
